### ISSUE TITLE
Cannot build the project. Maven error: Non-resolvable parent POM 

### ISSUE THREAD

**Issue by XxZhang2017** [confluentinc/kafka-connect-storage-common#72]
I have a problem with building kafka-connect-storage-common. I think the problem is maven cannot resolve the parent pom.xml. I search the Maven repository but I cannot find the jar file.

[FATAL] Non-resolvable parent POM for io.confluent:kafka-connect-storage-common-parent:[unknown-version]: Could not transfer artifact io.confluent:common:pom:5.1.0-SNAPSHOT from/to confluent (${confluent.maven.repo})

**Comment by cricket007** [comment]
@XxZhang2017 Please read https://github.com/confluentinc/kafka-connect-storage-common/wiki/FAQ

**Comment by XxZhang2017** [comment]
Hi,
I built it successfully. But I add something based your instructions.
Firstly, I add two dependecies in /common/utility-belt/pom.xml to install Common dependency,
       <dependency>
           <groupId>net.sf.jopt-simple</groupId>
           <artifactId>jopt-simple</artifactId>
           <version>5.0.4</version>
        </dependency>
        <dependency>
           <groupId>com.fasterxml.jackson.core</groupId>
           <artifactId>jackson-annotations</artifactId>
           <version>2.9.0</version>
        </dependency>
After fail to build I run mvn clean install .
Secondly, I edit /schema-registry/pom.xml file. 
from    <dependency>
                <groupId>uk.co.jemos.podam</groupId>
                <artifactId>podam</artifactId>
                <version>${podam.version}</version>
            </dependency>

to         <dependency>
                 <groupId>uk.co.jemos.podam</groupId>
                 <artifactId>podam</artifactId>
                 <version>6.0.2.RELEASE</version>
                 <scope>test</scope>
            </dependency>
Otherwise, I got the error,

Failed to collect dependencies at uk.co.jemos.podam:podam:jar:6.0.2.RELEASE: Failed to read artifact descriptor for uk.co.jemos.podam:podam:jar:6.0.2.RELEASE: Could not transfer artifact uk.co.jemos.podam:podam:pom:6.0.2.RELEASE from/to central

I am not sure that it is because I specify the <version> or I specify the <scope>, test.

**Comment by kkonstantine** [comment]
Building `master` and any release based branch that is meant to build a snapshots (e.g. branches that end in `.x` such as `5.0.x`, `4.1.x`, etc) require, first, to build locally any confluent dependencies. Snapshot versions are not published in public repos. 

Please re-open if this is still an issue.

**Comment by Dhruvsahu9** [comment]
It seems that the Confluent Repository URL is not being properly replaced with the property ${confluent.maven.repo}. I managed to get it working by actually replacing the url property ( line 74, pom.xml ) with the actual value.

So instead of this:

<repositories>
<repository>
<id>confluent</id>
<name>Confluent</name>
<url>${confluent.maven.repo}</url>
</repository>
</repositories>

I now have this:

<repositories>
<repository>
<id>confluent</id>
<name>Confluent</name>
<url>https://packages.confluent.io/maven/</url>
</repository>
</repositories>

I must have had cached all the Confluent dependencies during the demo. Sorry, for the inconvenience.

Hope it helps
